Add webpack package
This solves the issue with `Error: Cannot find module 'webpack'` in
this latest update to Next.js.

https://github.com/vercel/next.js/issues/21679